//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pb_net_api.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class credentials
    {
        public string id_user { get; set; }
        public string id_site { get; set; }
        public string ws { get; set; }
        public string status { get; set; }
        public string twofa { get; set; }
        public string id_credential { get; set; }
    }
}
