//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pb_net_api.EFModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string username { get; set; }
        public string password { get; set; }
        public string id_user { get; set; }
        public string date { get; set; }
        public string token { get; set; }
    }
}
